# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-01 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\uc131\uba85')),
                ('rank', models.CharField(max_length=20, verbose_name='\uc21c\uc704')),
                ('additions', models.CharField(max_length=255, verbose_name='\ube44\uace0')),
            ],
        ),
    ]
